## Basic Configuration

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true

baseurl = "https://chunjiw.com/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Chunji Wang"
title = "Chunji Wang"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Chunji Wang"
intro = "Data Scientist, Ph.D."
description = "\"It was good while it lasted.\""
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Chunji Wang's Personal Website"
keywords = "blog"

## Social Accounts
[params.social]
github = "chunjiw"
linkedin = "chunjiw"
# twitter = "chunjiw"
# facebook = "chunji.wang"
# stackoverflow = "4966531"
email = "chunjiw@gmail.com"

## Extras
[params.extra]
copyright = "© 2018 Chunji Wang. All Rights Reserved." 
poweredby = false
highlightjs = true

## Main Menu
[[menu.main]]
    name = "博客"
    identifier = "chinese"
    weight = 100
    url = "/cn/"
[[menu.main]]
    name = "blog"
    weight = 200
    identifier = "blog"
    url = "/blog/"
#[[menu.main]]
#    name = "about"
#    identifier = "about"
#    weight = 300
#    url = "/about/"
